version: '2'
services:

  vsftpd:
    image: kadock/vsftpd
    ports:
      - "21:21"
      - "10100-10199:10100-10199"
    environment:
      EXTERNAL_IP: "${EXTERNAL_IP}"
    volumes:
      - ${VSFTPD_DATA}:/var/vsftpd:Z
      - ${VSFTPD_ETC}:/etc/vsftpd:Z
