version: '2'
services:

  vsftpd:
    image: kadock/vsftpd
    ports:
      - "21:21"
      - "10100-10199:10100-10199"
    environment:
      EXTERNAL_IP: "172.20.20.22"
    volumes:
      - /srv/vsftpd/data:/var/vsftpd:Z
      - /srv/vsftpd/etc:/etc/vsftpd:ro
